---
style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 160
    excludeRawStrings: true

complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
  LongMethod:
    active: true
    threshold: 120
  LongParameterList:
    active: true
    functionThreshold: 12
    constructorThreshold: 12
