---
style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 160
    excludeRawStrings: true

complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
  LongMethod:
    active: true
    functionThreshold: 120
    constructorThreshold: 120
  LongParameterList:
    active: true
    threshold: 8
